CREATE TABLE USER_TOKENS(

ID INT AUTO_INCREMENT PRIMARY KEY,
USER_TOKEN VARCHAR(256) NOT NULL UNIQUE,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ISEXPIRED BIT NOT NULL DEFAULT 'FLASE',
USER_ID INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);